version: '3'

services:
  tuya:
    image: tuya:latest
    build:
      context: .
    privileged: true
    network_mode: "host"
    environment:
      - WLAN=wlan0
      - AP=vtrust-flash
      - GATEWAY=10.42.42.1
    volumes:
      - ./backups:/usr/bin/tuya-convert/backups
